kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: local
    app.kubernetes.io/name: cloud-native-pv
  name: cloud-native-pv
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cloud-native-store
  local:
    path: /mnt/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kubespray-postgres-0
---
kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: local
    app.kubernetes.io/name: cloud-native-pv2
  name: cloud-native-pv2
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cloud-native-store
  local:
    path: /mnt/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kubespray-postgres-1
