apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      tolerations:
        - key: "postgres-pool"
          operator: "Equal"
      containers:
        - name: pgpool
          image: pgpool/pgpool
          resources:
            requests:
              memory: "7Gi"
              cpu: "6"
            limits:
              memory: "7Gi"
              cpu: "6"
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cluster-prod-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-prod-app
                  key: password
            - name: PGPOOL_PASSWORD_ENCRYPTION_METHOD
              value: "scram-sha-256"
            - name: PGPOOL_ENABLE_POOL_PASSWD
              value: "true"
            - name: PGPOOL_SKIP_PASSWORD_ENCRYPTION
              value: "false"
          # The following settings are not required when not using the Pgpool-II PCP command.
          # To enable the following settings, you must define a secret that stores the PCP user's
          # username and password.
          #- name: PGPOOL_PCP_USER
          #  valueFrom:
          #    secretKeyRef:
          #      name: pgpool-pcp-secret
          #      key: username
          #- name: PGPOOL_PCP_PASSWORD
          #  valueFrom:
          #    secretKeyRef:
          #      name: pgpool-pcp-secret
          #      key: password
          volumeMounts:
            - name: pgpool-config
              mountPath: /config
            - name: pgpool-oiddir
              mountPath: /var/log/pgpool/oiddir
          #- name: pgpool-tls
          #  mountPath: /config/tls
      volumes:
        - name: pgpool-config
          configMap:
            name: pgpool-config
        - name: pgpool-oiddir
          persistentVolumeClaim:
            claimName: pgpool-pvc
      # Configure your own TLS certificate.
      # If not set, Pgpool-II will automatically generate the TLS certificate if ssl = on.
      #- name: pgpool-tls
      #  secret:
      #    secretName: pgpool-tls
---
apiVersion: v1
kind: Service
metadata:
  name: pgpool
spec:
  selector:
    app: pgpool
  ports:
    - name: pgpool-port
      protocol: TCP
      port: 9999
      targetPort: 9999

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pgpool
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-pgpool
  local:
    path: /mnt/pgpool
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kubespray-pgpool-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgpool-pvc
  namespace: default
spec:
  storageClassName: storage-pgpool
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
