apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbench-config
  labels:
    name: pgbench-config
data:
  .env.prod: |-
    environment=debug
    combinations_pipeline=data/full5pipeline.json
    db_rw_host=cluster-prod-rw
    testing_period=300
    pgbench_threads=40
    cluster_name=cluster-prod
    templates_folder="./data/templates"
    bot_token="6719777891:AAGsQ4mV3_bf5xPmPT-xV_WIu2np3CV-Hc0"
    bot_admin_id=5790906615
