apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgbench-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pgbench-role
  namespace: default
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - watch
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - watch
      - get
  - apiGroups:
      - postgresql.cnpg.io
    # resourceNames:
    #   - cluster-prod
    resources:
      - clusters
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - postgresql.cnpg.io
    # resourceNames:
    #   - cluster-prod
    resources:
      - clusters/status
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pgbench-rolebind
subjects:
  - kind: ServiceAccount
    name: pgbench-account
    namespace: default
roleRef:
  kind: Role
  name: pgbench-role
  apiGroup: rbac.authorization.k8s.io
