- name: Create dirs on pgbench
  hosts: pgbench
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Create dirs by root
      ansible.builtin.file:
        path: /mnt/pgbench
        state: directory
        mode: 0775

    - name: copy data
      copy:
        src: ./in_data/
        dest: /mnt/pgbench/

    # # для инициализации состояния
    # - name: Create dirs by root
    #   ansible.builtin.file:
    #     path: /mnt/pgbench/output
    #     state: directory
    #     mode: 0775

    # - name: Write backup script for each app
    #   shell: |
    #     echo '42' >> /mnt/pgbench/output/state
